/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    `maven-publish`
}

repositories {
    mavenLocal()
    mavenCentral()
}

dependencies {
    implementation("org.codehaus.groovy:groovy-all:2.0.5")
    implementation("com.google.guava:guava:30.0-jre")
    implementation("org.hsqldb:hsqldb:2.6.1")
    implementation("org.apache.logging.log4j:log4j-core:2.17.2")
    implementation("org.apache.logging.log4j:log4j-api:2.17.2")
    implementation("com.google.inject:guice:5.1.0")
    implementation("com.fasterxml.jackson.core:jackson-core:2.13.2")
    implementation("com.fasterxml.jackson.core:jackson-annotations:2.13.2")
    implementation("com.fasterxml.jackson.core:jackson-databind:2.13.2")
    implementation("io.netty:netty-all:4.1.75.Final")
    implementation("junit:junit:4.13.2")

    implementation("io.github.rkbalgi:iso4k:0.0.2")
}

group = "groupId"
version = "1.0-SNAPSHOT"
description = "keedoh"
java.sourceCompatibility = JavaVersion.VERSION_1_8
java.targetCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}
